version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: symphion_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A symphion worker --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379
    volumes:
      - .:/app

  celery-beat:
    build: .
    command: celery -A symphion beat --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379
    volumes:
      - .:/app

volumes:
  postgres_data:
  static_volume:
  media_volume: